repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: pretty-format-json
        args: [--autofix]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
        stages: [commit]
        args: [--branch, main, --branch, staging]
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: [django~=4.0]
        exclude: |
          (?x)^(
            ligapp/migrations/.*.py
          )$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-django
          - flake8-eradicate
          - flake8-print
          - flake8-requirements
          - flake8-todos
          - flake8-cognitive-complexity
          - flake8-docstrings
          - flake8-rst
        exclude: |
          (?x)^(
            ligapp/migrations/.*.py
          )$
        entry: flake8 --requirements-file=dev-requirements.txt

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: |
          (?x)^(
            ligapp/migrations/.*.py
          )$

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--target-version, py310]
        exclude: |
          (?x)^(
            ligapp/migrations/.*.py
          )$
