# -*- coding: utf-8 -*-
# Generated by Django 3.2.9 on 2021-12-06 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_played", models.DateTimeField(verbose_name="date played")),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="MultiSetMatch",
            fields=[
                (
                    "match_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ligapp.match",
                    ),
                ),
            ],
            bases=("ligapp.match",),
        ),
        migrations.CreateModel(
            name="TimedMatch",
            fields=[
                (
                    "match_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ligapp.match",
                    ),
                ),
                (
                    "minutes_played",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(60)]
                    ),
                ),
            ],
            bases=("ligapp.match",),
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(90)]
                    ),
                ),
                (
                    "second_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(90)]
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="ligapp.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("start_date", models.DateTimeField(verbose_name="start date")),
                ("participants", models.ManyToManyField(to="ligapp.Participant")),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="first_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches_first",
                to="ligapp.participant",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="second_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches_second",
                to="ligapp.participant",
            ),
        ),
    ]
