# -*- coding: utf-8 -*-
# Generated by Django 3.2.9 on 2021-12-06 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name_plural": "Matches"},
        ),
        migrations.AlterModelOptions(
            name="multisetmatch",
            options={"verbose_name_plural": "MultiSetMatches"},
        ),
        migrations.AlterModelOptions(
            name="timedmatch",
            options={"verbose_name_plural": "TimedMatches"},
        ),
        migrations.AddField(
            model_name="match",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="ligapp.season",
            ),
        ),
    ]
