# Generated by Django 3.2.9 on 2021-12-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['order']},
        ),
    ]
