# Generated by Django 3.2.9 on 2021-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapp', '0002_alter_set_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
    ]
