# Generated by Django 4.0.2 on 2022-03-07 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ligapp', '0003_season_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date_played'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='season',
            name='admins',
            field=models.ManyToManyField(related_name='season_admin_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
