# Generated by Django 4.0.2 on 2022-03-08 22:03

from django.db import migrations, models
import django.db.models.deletion
import ligapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("ligapp", "0005_player_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history",
                    models.JSONField(default=ligapp.models.ranking_history_entry),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="ligapp.player"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ligapp.season"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="ligapp.player"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ligapp.season"
                    ),
                ),
            ],
            options={
                "ordering": ["season", "rank"],
                "unique_together": {("season", "rank"), ("season", "player")},
            },
        ),
    ]
