# Generated by Django 4.0.2 on 2022-03-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligapp', '0006_rankinghistory_rank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('season', 'player')},
        ),
        migrations.AlterField(
            model_name='rank',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='ligapp.season'),
        ),
    ]
