# Generated by Django 4.0.2 on 2022-03-20 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligapp', '0007_alter_rank_unique_together_alter_rank_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('season', 'player')},
        ),
        migrations.AlterField(
            model_name='rank',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ranks', to='ligapp.player'),
        ),
        migrations.AlterField(
            model_name='rankinghistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='histories', to='ligapp.player'),
        ),
        migrations.AlterField(
            model_name='rankinghistory',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='ligapp.season'),
        ),
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('season', 'player'), ('season', 'rank')},
        ),
    ]
