# Generated by Django 4.0.2 on 2022-03-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligapp', '0008_alter_rank_unique_together_alter_rank_player_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('season', 'player')},
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ligapp.season'),
        ),
    ]
