# Generated by Django 4.0.2 on 2022-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapp', '0009_alter_rank_unique_together_alter_match_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
