# Generated by Django 4.0.2 on 2022-04-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapp', '0011_alter_player_user_alter_season_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='date_planned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date planned'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_played',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date played'),
        ),
    ]
