# Generated by Django 4.1.1 on 2022-09-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ligapp", "0012_match_completed_match_date_planned_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={
                "ordering": ["date_played"],
                "verbose_name": "match",
                "verbose_name_plural": "matches",
            },
        ),
        migrations.AlterModelOptions(
            name="multisetmatch",
            options={
                "verbose_name": "match for points",
                "verbose_name_plural": "matches for points",
            },
        ),
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["name"],
                "verbose_name": "player",
                "verbose_name_plural": "players",
            },
        ),
        migrations.AlterModelOptions(
            name="rank",
            options={
                "ordering": ["season", "rank"],
                "verbose_name": "player rank",
                "verbose_name_plural": "player ranks",
            },
        ),
        migrations.AlterModelOptions(
            name="rankinghistory",
            options={
                "verbose_name": "ranking history",
                "verbose_name_plural": "ranking histories",
            },
        ),
        migrations.AlterModelOptions(
            name="season",
            options={"verbose_name": "season", "verbose_name_plural": "seasons"},
        ),
        migrations.AlterModelOptions(
            name="set",
            options={
                "ordering": ["order"],
                "verbose_name": "set of points",
                "verbose_name_plural": "sets of points",
            },
        ),
        migrations.AlterModelOptions(
            name="timedmatch",
            options={
                "verbose_name": "match for time",
                "verbose_name_plural": "matches for time",
            },
        ),
    ]
